#define LEVEL_NAMES (ROM::game == 2 ? sml2_courses : sml3_courses)

const char *sml2_courses[] = {
    "00: Main - Intro",
    "01: Tree - Entrance",
    "02: Tree - MooJelly",
    "03: Tree - Bees",
    "04: Tree - Leaves",
    "05: Tree - Air",
    "06: Pumkin - Entrance",
    "07: Pumkin - Unbrellas",
    "08: Pumkin - Ghosts",
    "09: Pumkin - Pots",
    "10: Mario - Kogs",
    "11: Mario - Ballons",
    "12: Mario - Cannons",
    "13: Mario - Lego",
    "14: Turtle - Entrance",
    "15: Turtle - Ship",
    "16: Turtle - Whale",
    "17: Space - Entrance",
    "18: Space - Moon",
    "19: Space - Star",
    "20: Macro - Underground",
    "21: Macro - Ground",
    "22: Macro - House",
    "23: Macro - Books",
    "24: Wario's Castle",
    "25: Main - Scroll",
    "26: Turtle - B1 (ML2)",
    "27: Pumkin - B1",
    "28: Space - B1",
    "29: Tree - B1",
    "30: Marco - B1 (Scroll)",
    "31: Pumkin - B2 (Air)"
};

const char *sml3_courses[] = {
    "00: SS Teacup 1",
    "01: Parsley Woods 3",
    "02: Sherbet Land 2",
    "03: Stove Canyon 1",
    "04: Sherbet Land 3",
    "05: Mt. Teapot 4",
    "06: Mt. Teapot 1",
    "07: Rice Beach 1",
    "08: Sherbet Land 4",
    "09: Mt. Teapot 6",
    "10: Mt. Teapot 7",
    "11: SS Teacup 4",
    "12: Rice Beach 4",
    "13: Mt. Teapot 3",
    "14: Rice Beach 3",
    "15: Rice Beach 2",
    "16: Mt. Teapot 2",
    "17: Mt. Teapot 5",
    "18: Parsley Woods 5",
    "19: Parsley Woods 4",
    "20: SS Teacup 5",
    "21: Stove Canyon 2",
    "22: Stove Canyon 3",
    "23: Rice Beach 1 (FLOODED)",
    "24: Sherbet Land 6",
    "25: Rice Beach 5",
    "26: Parsley Woods 6",
    "27: Stove Canyon 5",
    "28: Stove Canyon 6",
    "29: Parsley Woods 2",
    "30: SS Teacup 2",
    "31: SS Teacup 3",
    "32: Sherbet Land 5",
    "33: Sherbet Land 1",
    "34: Syrup Castle 2",
    "35: Syrup Castle 3",
    "36: Rice Beach 3 (FLOODED)",
    "37: Syrup Castle 1",
    "38: Parsley Woods 1 (FLOODED)",
    "39: Stove Canyon 4",
    "40: Syrup Castle 4",
    "41: Rice Beach 6",
    "42: Parsley Woods 1 (DRAINED)"
};
